http:
  host: "0.0.0.0"
  port: "8092"
  basePath: "/api"
app:
  name: "sc-sys-wms-api"
  env: "local"
apikit:
  consoleEnabled: true
objectstore:
  persistent: false
  maxEntries: "10000"
  entryTtlHours: "24"
